### ISSUE TITLE
energy_per_hit_point filed missing from boat

### ISSUE THREAD

**Issue by clubpetey** [ludsoe/Factorio-MoMods#1]
Trying to run moTrans 0.1.5 under base 0.11.19 and received an error about "energy_per_hit_point" being missing.

So being new to modding I added this:
"energy_per_hit_point = 0.5,"

After line 47 in motrans/prototype/boat.lua

The "0.5" is the value used in DyTech's Tank, not sure if that the correct though.  But after adding this line I could load the mod.

Thanks for the great mod!
-pete

**Comment by ludsoe** [comment]
Fixed in latest mo-transport release.
