### ISSUE TITLE
bug wind speed

### ISSUE THREAD

**Issue by redmoonrus** [ludsoe/Factorio-MoMods#3]
Hello.
In moweather game.wind_speed 
in mopower game.windspeed turbine not workin and crash game

**Comment by Bouncebag** [comment]
"Error while running the event handler: **mopower**/control.lua:28 LuaGameScript doesn't contain key windspeed"
Using Factorio 12.2 and mopower  0.3.02

It throws the error on save files using the mopower mod (save from factorio 11.22 with mopower 0.1.985 used)
and also when placing new wind turbine in a new game.
